"""Single source of truth for allowed taxonomy values shared across pipeline scripts."""

ALLOWED_CATEGORIES = {
    "AEW&C",
    "Attack / Strike",
    "Business Jet",
    "Cargo Freighter",
    "Electronic Warfare",
    "Fighter / Interceptor",
    "Helicopter - Attack",
    "Helicopter - Maritime",
    "Helicopter - Transport",
    "Helicopter - Utility",
    "ISR / Surveillance",
    "Maritime Patrol",
    "Passenger - Narrowbody",
    "Passenger - Widebody",
    "Regional Passenger",
    "Special Mission",
    "Strategic Airlift",
    "Tactical Airlift",
    "Tanker",
    "Trainer",
    "UAV - Combat",
    "UAV - Recon",
    "UAV - Utility",
    "Utility",
}

VALID_TAG1 = {
    "Tactical Transport",
    "Strategic Transport",
    "Maritime Patrol",
    "ISR",
    "Early Warning",
    "Air Superiority",
    "Strike",
    "Close Air Support",
    "Refueling",
    "Training",
    "Utility",
    "Electronic Warfare",
}

VALID_TAG2 = {
    "STOL",
    "Long Range",
    "Short Runway",
    "Heavy Lift",
    "Medium Lift",
    "Multi-Role",
    "All-Weather",
    "High Endurance",
    "Aerial Refueling",
    "Carrier Capable",
    "Amphibious",
    "Basic Trainer",
    "Light Lift",
    "Low Altitude",
}

VALID_TAG3 = {
    "Twin Turboprop",
    "Turboprop",
    "Twin Engine",
    "Quad Engine",
    "Jet",
    "High Wing",
    "Low Wing",
    "Rear Ramp",
    "Side Door",
    "Pressurized",
    "Sensor Suite",
    "Modular Cabin",
    "Single Engine",
    "Rotorcraft",
}
